<?php
declare(strict_types=1);
/**
 * Plugin Name: Matchmaker
 * Description: Matchmaker plugin skeleton (scaffolded).
 * Version: 0.1.0
 * Author: Generated by Copilot
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

define('MATCHMAKER_VERSION', '0.1.0');
define('MATCHMAKER_PATH', plugin_dir_path(__FILE__));
define('MATCHMAKER_URL', plugin_dir_url(__FILE__));

// Prefer Composer autoload (PSR-4 + files). Fall back to legacy includes.
if (file_exists(MATCHMAKER_PATH . 'vendor/autoload.php')) {
    require_once MATCHMAKER_PATH . 'vendor/autoload.php';
} else {
    foreach (glob(MATCHMAKER_PATH . 'includes/*.php') as $file) {
        require_once $file;
    }
}

// Always ensure global helper functions are loaded (Composer files[] handles this,
// but we explicit-require as a safety net for environments where autoload is stale).
if (!function_exists('mm_enqueue_user_matching_job')) {
    require_once MATCHMAKER_PATH . 'includes/functions.php';
}

// Ensure Action Scheduler is loaded cleanly if available
if (!function_exists('as_enqueue_async_action') && file_exists(MATCHMAKER_PATH . 'vendor/woocommerce/action-scheduler/action-scheduler.php')) {
    require_once MATCHMAKER_PATH . 'vendor/woocommerce/action-scheduler/action-scheduler.php';
}

// Initialize core classes
add_action('plugins_loaded', function () : void {
    if (class_exists('\Matchmaker\DB_Migrator')) {
        \Matchmaker\DB_Migrator::instance();
    }
    if (class_exists('\Matchmaker\PMPro_Sync')) {
        \Matchmaker\PMPro_Sync::instance();
    }
    if (class_exists('\Matchmaker\Admin_Portal')) {
        \Matchmaker\Admin_Portal::instance();
    }
    if (class_exists('\Matchmaker\Free_Reg_Handler')) {
        \Matchmaker\Free_Reg_Handler::instance();
    }
    if (class_exists('\Matchmaker\Auth_Redirects')) {
        \Matchmaker\Auth_Redirects::instance();
    }
    if (class_exists('\Matchmaker\Form_Handler')) {
        \Matchmaker\Form_Handler::instance();
    }
    if (class_exists('\Matchmaker\Field_Generator')) {
        \Matchmaker\Field_Generator::instance();
    }
    if (class_exists('\Matchmaker\Matching_Engine')) {
        \Matchmaker\Matching_Engine::instance();
    }
});

// Activation / Deactivation hooks
register_activation_hook(__FILE__, function () : void {
    if (!function_exists('as_enqueue_async_action') && file_exists(MATCHMAKER_PATH . 'vendor/woocommerce/action-scheduler/action-scheduler.php')) {
        require_once MATCHMAKER_PATH . 'vendor/woocommerce/action-scheduler/action-scheduler.php';
    }
    if (class_exists('\\Matchmaker\\DB_Migrator')) {
        \Matchmaker\DB_Migrator::activate();
    }
    if (class_exists('\\Matchmaker\\Matching_Engine')) {
        \Matchmaker\Matching_Engine::activate();
    }
});

register_deactivation_hook(__FILE__, function () : void {
    if (!function_exists('as_enqueue_async_action') && file_exists(MATCHMAKER_PATH . 'vendor/woocommerce/action-scheduler/action-scheduler.php')) {
        require_once MATCHMAKER_PATH . 'vendor/woocommerce/action-scheduler/action-scheduler.php';
    }
    if (class_exists('\\Matchmaker\\Matching_Engine')) {
        \Matchmaker\Matching_Engine::deactivate();
    }
});

